# Basic
edition = "2021"
max_width = 100
use_small_heuristics = "Max"

# Imports
imports_granularity = "Preserve"
reorder_imports = false

# Consistency
newline_style = "Unix"

# Misc
chain_width = 80
spaces_around_ranges = false
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
# trailing_semicolon = false
# use_field_init_shorthand = true
# where_single_line = true

# Format comments
comment_width = 100
wrap_comments = true

